spring.application.name=Pdf_Chat_bot
deepseek.api.key=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


spring.datasource.url=jdbc:mysql://localhost:3306/pdfchatbot?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=BahaaKhaled@1

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=8081

